# Generated by Django 3.2 on 2021-11-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('pid', models.IntegerField(blank=True, default=0, null=True)),
                ('isread', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('content', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
