# Generated by Django 3.2 on 2021-12-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isdeal',
            field=models.BooleanField(default=False),
        ),
    ]
