# Generated by Django 3.2 on 2021-12-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_isdeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
