# Generated by Django 3.2 on 2021-12-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_message_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('mid', models.IntegerField()),
                ('type', models.IntegerField(default=1)),
                ('reply', models.TextField(blank=True, null=True)),
                ('isdeal', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('url', models.CharField(default='default_profile.png', max_length=50)),
            ],
        ),
    ]
