# Generated by Django 3.2 on 2021-12-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
