# Generated by Django 3.2 on 2021-12-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_message_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
