# Generated by Django 3.2 on 2021-11-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='download',
            field=models.IntegerField(default=0),
        ),
    ]
