# Generated by Django 3.2 on 2021-11-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_scholar_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='cite',
            field=models.IntegerField(default=0),
        ),
    ]
