# Generated by Django 3.2 on 2021-10-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('author', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(default=-1)),
                ('cite', models.IntegerField(default=-1)),
                ('url', models.TextField(blank=True, null=True)),
                ('lang', models.CharField(blank=True, max_length=20, null=True)),
                ('doi', models.CharField(blank=True, max_length=50, null=True)),
                ('field', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
