# Generated by Django 3.2 on 2021-11-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='download',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
