# Generated by Django 3.2 on 2021-11-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_paper_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='download',
            field=models.IntegerField(default=0),
        ),
    ]
