# Generated by Django 3.2 on 2021-12-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0005_favor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('time', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('reply', models.IntegerField()),
                ('replyuid', models.IntegerField(blank=True, default=0, null=True)),
                ('replyname', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
