# Generated by Django 3.2 on 2021-12-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0007_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='uid1',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='uid2',
        ),
        migrations.AddField(
            model_name='relation',
            name='name1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='relation',
            name='name2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
