# Generated by Django 3.2 on 2021-12-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0008_auto_20211211_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='favors',
            field=models.IntegerField(default=0),
        ),
    ]
