# Generated by Django 3.2 on 2021-12-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0010_alter_paper_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
