# Generated by Django 3.2 on 2021-12-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0011_alter_paper_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='venue',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
