# Generated by Django 3.2 on 2021-12-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0012_alter_paper_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='cite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
